### ISSUE TITLE
Fix IBM Q API Access

### ISSUE THREAD

**Issue by salmma** [UST-QuAntiL/qprov#14]
IBM Q changed the API such that QProv is not able anymore to login and access the QPU data.

New **login** mechanism:
curl --location 'https://auth.quantum-computing.ibm.com/api/users/loginWithToken' \
--header 'Content-Type: application/json' \
--data '{"apiToken": "YOUR-IBMQ-TOKEN"}'

Then, take the "id" in the response body to login in https://api.quantum-computing.ibm.com/explorer/ to get access to the API, also offering the QPU data.

**Comment by salmma** [comment]
https://github.com/UST-QuAntiL/qprov/tree/bugfix/ibm_authentication is a first approach to fix it

**Comment by wederbn** [comment]
Fixed by #15
